# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  database: ms.fix.me.app_development
  encoding: utf8
  username: msdev
  password: password
  host: 127.0.0.1

development_replica:
  adapter: mysql2
  database: ms.fix.me.app_development
  encoding: utf8
  username: msdev
  password: password
  host: localhost

test: &test
  adapter: mysql2
  database: ms.fix.me.app_test
  encoding: utf8
  username: msdev
  password: password
  host: localhost
  
test_replica:
  adapter: mysql2
  database: ms.fix.me.app_test
  encoding: utf8
  username: msdev
  password: password
  host: localhost

cucumber:
  <<: *test